module.exports = {
  content: [
    '**/*.composition.{jsx,tsx,ts,js}',
    '**/*.tailwind.{jsx,tsx,ts,js,html}',
    '**/**/*.composition.{jsx,tsx,ts,js}',
    '**/**/*.tailwind.{jsx,tsx,ts,js,html}',
    '**/**/**/*.composition.{jsx,tsx,ts,js}',
    '**/**/**/*.tailwind.{jsx,tsx,ts,js,html}',
    '**/**/**/**/*.composition.{jsx,tsx,ts,js}',
    '**/**/**/**/*.tailwind.{jsx,tsx,ts,js,html}',
    '**/**/**/**/**/*.composition.{jsx,tsx,ts,js}',
    '**/**/**/**/**/*.tailwind.{jsx,tsx,ts,js,html}',
    '**/**/**/**/**/**/*.composition.{jsx,tsx,ts,js}',
    '**/**/**/**/**/**/*.tailwind.{jsx,tsx,ts,js,html}',
    '**/**/**/**/**/**/**/*.composition.{jsx,tsx,ts,js}',
    '**/**/**/**/**/**/**/*.tailwind.{jsx,tsx,ts,js,html}',
    '**/**/**/**/**/**/**/**/*.composition.{jsx,tsx,ts,js}',
    '**/**/**/**/**/**/**/**/*.tailwind.{jsx,tsx,ts,js,html}',
  ],
  important: true,
};
